# Generated by Django 6.0.3 on 2026-05-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adreswysylki',
            options={'verbose_name_plural': 'Adres Wysylki'},
        ),
    ]
