# Generated by Django 6.0.3 on 2026-05-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_adreswysylki_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adreswysylki',
            name='imie',
        ),
        migrations.AddField(
            model_name='adreswysylki',
            name='imie_nazwisko',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
