# Generated by Django 6.0.3 on 2026-05-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_adreswysylki_imie_adreswysylki_imie_nazwisko'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='adres1',
            new_name='wysylka_adres1',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='adres2',
            new_name='wysylka_adres2',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='email',
            new_name='wysylka_email',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='imie_nazwisko',
            new_name='wysylka_imie_nazwisko',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='kod_pocztowy',
            new_name='wysylka_kod_pocztowy',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='miasto',
            new_name='wysylka_miasto',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='panstwo',
            new_name='wysylka_panstwo',
        ),
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='wojewodztwo',
            new_name='wysylka_wojewodztwo',
        ),
    ]
