# Generated by Django 6.0.3 on 2026-05-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_adres1_adreswysylki_wysylka_adres1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adreswysylki',
            old_name='wysylka_panstwo',
            new_name='wysylka_kraj',
        ),
    ]
