# Generated by Django 6.0.3 on 2026-05-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_wysylka_panstwo_adreswysylki_wysylka_kraj'),
        ('sklep', '0016_rename_panstwo_profil_kraj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('wysylka_adres', models.TextField(max_length=10000)),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zamowienia',
            },
        ),
        migrations.CreateModel(
            name='ZamowieniaProdukty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveBigIntegerField(default=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zamowienie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.zamowienia')),
            ],
            options={
                'verbose_name_plural': 'Zamowienia Produkty',
            },
        ),
    ]
