# Generated by Django 6.0.3 on 2026-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_zamowienia_zamowieniaprodukty'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='czy_wyslane',
            field=models.BooleanField(default=False),
        ),
    ]
