# Generated by Django 6.0.3 on 2026-05-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_zamowienia_czy_wyslane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zamowienia',
            old_name='czy_wyslane',
            new_name='wyslane',
        ),
    ]
