# Generated by Django 6.0.3 on 2026-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_czy_wyslane_zamowienia_wyslane'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='data_wyslania',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
