# Generated by Django 6.0.3 on 2026-03-23 19:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('haslo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opis', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('zdjecie', models.ImageField(upload_to='uploads/product/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sklep.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=1)),
                ('adres', models.CharField(blank=True, default='', max_length=100)),
                ('telefon', models.CharField(blank=True, default='', max_length=15)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.customer')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.product')),
            ],
        ),
    ]
