# Generated by Django 6.0.3 on 2026-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='czy_promocja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promocja_cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='haslo',
            field=models.CharField(max_length=50),
        ),
    ]
