# Generated by Django 6.0.3 on 2026-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_product_czy_promocja_product_promocja_cena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='czy_promocja',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promocja_cena',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
