# Generated by Django 6.0.3 on 2026-04-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_product_czy_promocja_product_promocja_cena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='czy_promocja',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promocja_cena',
        ),
    ]
