# Generated by Django 6.0.3 on 2026-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_remove_product_czy_promocja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='czy_promocja',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promocja_cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
