# Generated by Django 6.0.3 on 2026-04-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_rename_category_kategoria_rename_customer_klient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='czy_promocja',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='promocja_cena',
        ),
    ]
