# Generated by Django 6.0.3 on 2026-04-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_remove_produkt_czy_promocja_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategoria',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Klient',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Zamowienie',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Produkt',
            new_name='Product',
        ),
    ]
