# Generated by Django 6.0.3 on 2026-04-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0010_product_czy_promocja_product_promocja_cena'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategoria',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Klient',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Produkt',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Zamowienia',
        ),
    ]
