# Generated by Django 6.0.3 on 2026-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0011_rename_category_kategoria_rename_customer_klient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='zamowienia',
            options={'verbose_name_plural': 'Zamowienia'},
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='category',
            new_name='kategoria',
        ),
    ]
