# Generated by Django 6.0.3 on 2026-05-07 17:58

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0012_alter_kategoria_options_alter_klient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='adres',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('adres1', models.CharField(blank=True, max_length=150)),
                ('adres2', models.CharField(blank=True, max_length=150)),
                ('miasto', models.CharField(blank=True, max_length=60)),
                ('wojewodztwo', models.CharField(blank=True, max_length=40)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=15)),
                ('panstwo', models.CharField(blank=True, max_length=40)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
