# Generated by Django 6.0.3 on 2026-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0013_alter_zamowienia_adres_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AddField(
            model_name='profil',
            name='koszyk_old',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
