# Generated by Django 6.0.3 on 2026-05-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0014_alter_profil_options_profil_koszyk_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
