# Generated by Django 6.0.3 on 2026-05-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0015_alter_klient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='panstwo',
            new_name='kraj',
        ),
    ]
